'use client';
import { Inter } from 'next/font/google';
import './globals.css';
import { Provider } from '@gadgetinc/react';
import { api } from '../api';
import { FileProvider } from './fileDetails';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <FileProvider>
          <Provider api={api}>{children}</Provider>
        </FileProvider>
      </body>
    </html>
  );
}
